image = "jfrog.svc.cscs.ch/docker-group-csstaff/alps-images/ngc-nemo:25.11.01-alps3"

workdir = "${SCRATCH}"

mounts = [
  "/capstor",
  "/iopsstor",
  "${SCRATCH}:${SCRATCH}",
  "${HOME}:${HOME}",
  "/tmp:/tmp",
  "/var/spool/slurmd:/var/spool/slurmd",
]

writable = true

[env]
PMIX_MCA_psec = "native"

[annotations]
com.hooks.cxi.enabled = "true"
com.hooks.netstack.source = "artifact"